language: node_js
node_js: '6.2.1'

branches:
  only:
    - master

before_install:
  - npm install bower -g
  - npm install gulp -g

script:
  - npm prune
  - npm install
  - npm install wrench
  - ls node_modules/
  - gulp clean