language: node_js
node_js:
  - '6'

branches:
  only:
    - master

before_install:
  - npm install -g bower
  - npm install -g gulp

script:
  - npm install
  - bower install
  - gulp clean
  - gulp dist --verbose

cache:
  directories:
    - bower_components
    - node_components

notifications:
  email:
    - weberamaral@outlook.com

